export const SET_NEWS_LIST = 'NEWS::SET_NEWS_LIST'
export const SET_ERROR_STATUS = 'NEWS::SET_ERROR_STATUS'
export const SET_LOADING_STATUS = 'NEWS::SET_LOADING_STATUS'
export const SET_IDLE_STATUS = 'NEWS::SET_IDLE_STATUS'